[alias]
drun = "run --features bevy/dynamic_linking"
dbuild = "build --features bevy/dynamic_linking"
dtest = "test --features bevy/dynamic_linking"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
